language: java
jdk:
  - openjdk8
install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get update -qq
  - sudo apt-get install qt510-meta-minimal
script:
  - source /opt/qt510/bin/qt510-env.sh
  - mkdir build
  - cd build
  - qmake -v
  - qmake ../PetStore/PetStore.pro
  - make
  - ./PetStore
