language: java
jdk:
  - openjdk8
install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt5123-trusty
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qt5-default qttools5-dev-tools
script:
  #  - source ~/virtualenv/python3.6/bin/activate
  #- pip3 install conan
  - mkdir build
  - cd build
    #- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    #- conan install .. --build missing
    #- source activate_run.sh
  - qmake -v
  - qmake ../PetStore/PetStore.pro
  - make
  - ./PetStore
