language: java
jdk:
  - openjdk8
addons:
  apt:
    sources:
      - beineri/opt-qt-5.10.1-trusty
    packages:
      - qt510-meta-minimal
script:
  - source /opt/qt510/bin/qt510-env.sh
  - mkdir build
  - cd build
  - qmake -v
  - qmake ../PetStore/PetStore.pro
  - make
  - ./PetStore
